version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-js-app-ec2
permissions:
  - object: /home/ubuntu/node-js-app-ec2
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: script/after_install.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: script/start_app.sh
      runas: ubuntu
      timeout: 300
