version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-js-app-ec2
permissions:
  - object: /home/ubuntu/node-js-app-ec2
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - runas: ubuntu
      timeout: 300
      script: scripts/before_install.sh
  AfterInstall:
    - runas: ubuntu
      timeout: 300
      script: scripts/after_install.sh
  ApplicationStart:
    - runas: ubuntu
      timeout: 300
      script: scripts/start_app.sh
